apiVersion: batch/v1
kind: Job
metadata:
  name: training-job
  namespace: training        
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: training-job
    spec:
      ttlSecondsAfterFinished: 60
      tolerations:
        - key: nvidia.com/gpu
          operator: Equal
          value: "true"
          effect: NoSchedule


      nodeSelector:
        karpenter.sh/capacity-type: spot

      containers:
      - name: trainer
        image: 862503802102.dkr.ecr.eu-west-1.amazonaws.com/training-job:latest
        imagePullPolicy: Always

        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1

        env:
        - name: MODEL_BUCKET
          value: "training-bucket-86250380"   
        - name: EPOCHS
          value: "15"

      restartPolicy: Never